cli:
  image: webdevops/php-dev
  volumes:
  - ./app:/app
  working_dir: /app
  environment:
    PHP_IDE_CONFIG: serverName=php-cli
    XDEBUG_CONFIG: idekey=PHPSTORM
    XDEBUG_REMOTE_AUTOSTART: 1
    XDEBUG_REMOTE_CONNECT_BACK: 0
    XDEBUG_REMOTE_ENABLE: 1
    XDEBUG_REMOTE_HOST: docker.for.mac.localhost # 172.17.0.1 for linux users
    XDEBUG_PROFILER_ENABLE: 0
